import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css';
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// navgation bar dinamic call by cleint side
const DinamicNav = dynamic(() => import("./components/navgationbar/Nav"), {
  ssr: false,
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DinamicNav />
        {children}
        </body>
    </html>
  );
}
