import type { Metadata } from "next";
import "./globals.css";
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css';
import Nav from "./components/navgationbar/Nav";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "dragon_store",
  description: "Generated by create next app",
};

// Hnadel State management
import { Providers } from "./RTK/provider"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}